# Generated by Django 5.0.7 on 2024-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_city_branch_city_moviead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='on_screen_movies',
        ),
        migrations.AddField(
            model_name='city',
            name='on_screen_movies',
            field=models.ManyToManyField(to='cinema.movie'),
        ),
    ]
