# Generated by Django 5.0.7 on 2024-08-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_remove_branch_on_screen_movies_city_on_screen_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/preview-images'),
        ),
    ]
