# Generated by Django 5.0.7 on 2024-08-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_alter_moviead_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviead',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
