# Generated by Django 5.0.7 on 2024-08-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moviead',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
