# Generated by Django 5.0.7 on 2024-08-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_room_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='now_playing',
            field=models.BooleanField(default=False),
        ),
    ]
