# Generated by Django 5.0.7 on 2024-08-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_rename_now_playing_movie_coming_soon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
