# Generated by Django 5.0.7 on 2024-08-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_weekday_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rows',
        ),
        migrations.AddField(
            model_name='room',
            name='number_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
