# Generated by Django 5.0.7 on 2024-08-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_remove_room_columns_remove_room_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.room'),
            preserve_default=False,
        ),
    ]
