# Generated by Django 5.0.7 on 2024-08-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_shift_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
