# Generated by Django 5.0.7 on 2024-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_remove_shift_weekdays_shift_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
