# Generated by Django 5.0.7 on 2024-08-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0029_alter_city_id_alter_moviead_id_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
    ]
