# Generated by Django 5.0.7 on 2024-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0030_remove_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
