# Generated by Django 5.0.7 on 2024-08-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0031_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
    ]
