# Generated by Django 5.0.7 on 2024-08-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0032_remove_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='opens_at',
            field=models.TimeField(default='12:30'),
        ),
    ]
