# Generated by Django 5.0.7 on 2024-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0033_alter_room_opens_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSessionSeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
    ]
