# Generated by Django 5.0.7 on 2024-08-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0034_selectedsessionseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionChannel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SessionGroup',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('channel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.sessionchannel')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.sessiongroup')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedSessionSeat',
        ),
    ]
