# Generated by Django 5.0.7 on 2024-08-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0035_sessionchannel_sessiongroup_sessionseat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionseat',
            name='group_name',
        ),
    ]
