# Generated by Django 5.0.7 on 2024-08-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0036_remove_sessionseat_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionchannel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SessionSeat',
        ),
    ]
