# Generated by Django 5.0.7 on 2024-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0037_sessionchannel_data_delete_sessionseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionchannel',
            name='data',
            field=models.JSONField(default={'seats': []}),
        ),
    ]
