# Generated by Django 5.0.7 on 2024-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0038_alter_sessionchannel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionchannel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
