# Generated by Django 5.0.7 on 2024-08-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0039_alter_sessionchannel_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionchannel',
            old_name='group_name',
            new_name='group',
        ),
    ]
