# Generated by Django 5.0.7 on 2024-08-29 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0042_discounttype_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(blank=True, choices=[('age', 'Age'), ('day', 'Day')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('tickets', models.ManyToManyField(to='cinema.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.discount')),
            ],
        ),
        migrations.DeleteModel(
            name='DiscountType',
        ),
    ]
