# Generated by Django 5.0.7 on 2024-09-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0044_alter_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number_seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='repeat_every_day',
        ),
        migrations.AddField(
            model_name='bill',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='bills/qr-codes'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.tickettype'),
        ),
    ]
