# Generated by Django 5.0.7 on 2024-09-02 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0045_remove_ticket_number_seats_remove_ticket_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='bill',
            name='seats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.session'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
