# Generated by Django 5.0.7 on 2024-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0046_remove_bill_tickets_remove_ticket_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
