apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: django-q
  name: django-q
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django-q
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: django-q
    spec:
      containers:
        - args:
            - python
            - manage.py
            - qcluster
          image: django-q
          name: django-q
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /backend
              name: django-q-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: django-q-cm0
          name: django-q-cm0
