services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    network_mode: host
  djangoq:
    build: ./backend
    volumes:
      - ./backend:/backend
    command: python manage.py qcluster
    network_mode: host
  api:
    build: ./backend       
    volumes:
      - ./backend:/backend
    command: gunicorn -b :8000 capstone.wsgi:application
    depends_on:
      - djangoq
      - redis
    network_mode: host
  web:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    network_mode: host


