services:
  api:
    build: ./backend       
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 
    depends_on:
      - django-q
    network_mode: host
  django-q:
    build: ./backend
    volumes:
      - ./backend:/backend
    command: python manage.py qcluster
    network_mode: host
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    network_mode: host


